#' Generate Typo Documentation
#'
#' @description
#' Generates Generic Typo Documentation
#'
#' @param incorrect_spellings
#' The new incorrect spelling(s) of the function
#'
#' @param correct_spelling
#' The correct spelling of the function
#'
#' @param methods
#' Additional methods to be implemented.
#' Possible values include `"<-"`
#'
#' @param dir
#' Directory for the generated file to be stored
#'
#'
#'
#' @examples
#' Gen_typo("nameS","names",methods = c("<-"))
#' Gen_typo("typoef","typeof")

Gen_typo <- function(incorrect_spellings,correct_spelling,methods=NULL,pkg="base",dir="R/")
{
  .incorrect <- incorrect_spellings
  .correct <- correct_spelling
  .pkg <- pkg
  .methods <- methods
  .pkg_correct <- paste0(.pkg,"::",.correct)


  .incorrect_preamble <- paste0("`",.incorrect,"()`")
  if(length(.incorrect)==1)
  {
    .incorrect_preamble <- paste(.incorrect_preamble,collapse="")
  } else {
    .incorrect_preamble <- paste("any of\n\n*",
                                 paste(.incorrect_preamble,collapse="\n*"))
  }


  .preamble <- c("#' @name ",.correct,"-typo\n",
                 "#'\n",
                 "#' @title\n",
                 "#' Typo of the `",.correct,"()` function\n",
                 "#'\n",
                 "#' @description\n",
                 "#' Runs the [",.pkg_correct,"()] function when ",
                      .incorrect_preamble," is called and outputs\n",
                 "#' a warning to the user to alert them to the typo\n",
                 "#'\n",
                 "#' @param ... arguments passed to [",.pkg_correct,"()]\n",
                 "#'\n",
                 "#'\n",
                 "#' @seealso [",.pkg_correct,"()]\n",
                 "#'\n",
                 "NULL\n",
                 "\n",
                 "# Do not edit this file, use the Gen_typo.R to edit Documentation")

  .functions <- lapply(.incorrect,
                       Gen_typo_function,
                       .correct=.correct,
                       .pkg=.pkg)

  if(length(.methods)>0)
  {
    for(iM in .methods)
    {
      .functions <- c(.functions,
                      lapply(.incorrect,Gen_typo_method,
                                      .correct=.correct,
                                      .pkg=.pkg,
                                      .method=iM))
    }
  }

  .functions <- unlist(.functions)
  .functions <- paste0("\n\n",
                      "#' @rdname ",.correct,"-typo\n",
                      .functions)

  .out <- c(.preamble,.functions,"\n")

  .out <- paste0(.out,collapse="")

  .file <- paste0(dir,.correct,".R")

  writeLines(.out,.file)

  return(.file)
}

Gen_typo_function <- function(.incorrect,.correct,.pkg)
{
  .out <- c(.incorrect," <- function(...)\n",
            "{\n",
            "  require(",.pkg,")\n",
            "  warning(\"Typo - ",.incorrect,
                " instead of ",.correct,"\",call.=F)\n",
            "  ",.pkg,"::",.correct,"(...)\n",
            "}")
  return(paste0(.out,collapse=""))
}

Gen_typo_method <- function(.incorrect,.correct,.pkg,.method)
{
  if(.method == "<-")
  {
    .incorrect_new <- paste0("`",.incorrect,.method,"`")
    .correct_new <- paste0("`",.correct,.method,"`")
  } else if(.method == "print"){

    .incorrect_new <- paste0(.method,".",.incorrect)
    .correct_new <- paste0(.method,".",.correct)

  } else stop("Method not support yet")

  .out <- c(.incorrect_new," <- function(...)\n",
            "{\n",
            "  require(",.pkg,")\n",
            "  warning(\"Typo - ",.incorrect,
            " instead of ",.correct,"\",call.=F)\n",
            "  ",.pkg,"::",.correct_new,"(...)\n",
            "}")
  return(paste0(.out,collapse=""))

}
