#' @name names-typo
#'
#' @title
#' Typo of the `names()` function
#'
#' @description
#' Runs the [base::names()] function when `nameS()` is called and outputs
#' a warning to the user to alert them to the typo
#'
#' @param ... arguments passed to [base::names()]
#'
#'
#' @seealso [base::names()]
#'
NULL

# Do not edit this file, use the Gen_typo.R to edit Documentation

#' @rdname names-typo
nameS <- function(...)
{
  require(base)
  warning("Typo - nameS instead of names",call.=F)
  base::names(...)
}

#' @rdname names-typo
`nameS<-` <- function(...)
{
  require(base)
  warning("Typo - nameS instead of names",call.=F)
  base::`names<-`(...)
}

