#' @name typeof-typo
#'
#' @title
#' Typo of the `typeof()` function
#'
#' @description
#' Runs the [base::typeof()] function when `typoef()` is called and outputs
#' a warning to the user to alert them to the typo
#'
#' @param ... arguments passed to [base::typeof()]
#'
#'
#' @seealso [base::typeof()]
#'
NULL

# Do not edit this file, use the Gen_typo.R to edit Documentation

#' @rdname typeof-typo
typoef <- function(...)
{
  require(base)
  warning("Typo - typoef instead of typeof",call.=F)
  base::typeof(...)
}

