on:
  push:
    branches: master

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install current package
        run: R CMD INSTALL .
      - name: Run Setup File
        run: Rscript "setup.R"
      - name: Commit results
        run: |
          git commit README.md -m 'Auto-Rendered Package' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
